//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app.com.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_cus_contact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public app_cus_contact()
        {
            this.app_cus_main = new HashSet<app_cus_main>();
        }
    
        public int id { get; set; }
        public Nullable<int> contact_code { get; set; }
        public string tele_number { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string brief_location { get; set; }
        public string gps_cordinates { get; set; }
        public Nullable<int> country_code { get; set; }
        public string tele_number2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<app_cus_main> app_cus_main { get; set; }
    }
}
