//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app.com.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public app_branch()
        {
            this.app_cus_main = new HashSet<app_cus_main>();
        }
    
        public int id { get; set; }
        public int bran_code { get; set; }
        public string branch_name { get; set; }
        public Nullable<int> bran_type_code { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string assets { get; set; }
    
        public virtual app_bran_type app_bran_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<app_cus_main> app_cus_main { get; set; }
    }
}
