//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app.com.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<app_age_cate> app_age_cate { get; set; }
        public virtual DbSet<app_bran_type> app_bran_type { get; set; }
        public virtual DbSet<app_branch> app_branch { get; set; }
        public virtual DbSet<app_countries> app_countries { get; set; }
        public virtual DbSet<app_cus_contact> app_cus_contact { get; set; }
        public virtual DbSet<app_cus_doc> app_cus_doc { get; set; }
        public virtual DbSet<app_cus_other_info> app_cus_other_info { get; set; }
        public virtual DbSet<app_cus_type> app_cus_type { get; set; }
        public virtual DbSet<app_doc_type> app_doc_type { get; set; }
        public virtual DbSet<app_gender> app_gender { get; set; }
        public virtual DbSet<app_home_type> app_home_type { get; set; }
        public virtual DbSet<app_kin_details> app_kin_details { get; set; }
        public virtual DbSet<app_kin_type> app_kin_type { get; set; }
        public virtual DbSet<app_occupation> app_occupation { get; set; }
        public virtual DbSet<app_rel_office> app_rel_office { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<app_cus_main> app_cus_main { get; set; }
    
        public virtual int app_sp_Deleteapp_age_cate(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Deleteapp_age_cate", idParameter);
        }
    
        public virtual int app_sp_Deleteapp_bran_type(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Deleteapp_bran_type", idParameter);
        }
    
        public virtual int app_sp_Deleteapp_branch(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Deleteapp_branch", idParameter);
        }
    
        public virtual int app_sp_Deleteapp_countrie(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Deleteapp_countrie", idParameter);
        }
    
        public virtual int app_sp_Deleteapp_cus_contact(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Deleteapp_cus_contact", idParameter);
        }
    
        public virtual int app_sp_Deleteapp_cus_doc(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Deleteapp_cus_doc", idParameter);
        }
    
        public virtual int app_sp_Deleteapp_cus_main(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Deleteapp_cus_main", idParameter);
        }
    
        public virtual int app_sp_Deleteapp_cus_other_info(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Deleteapp_cus_other_info", idParameter);
        }
    
        public virtual int app_sp_Deleteapp_cus_type(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Deleteapp_cus_type", idParameter);
        }
    
        public virtual int app_sp_Deleteapp_doc_type(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Deleteapp_doc_type", idParameter);
        }
    
        public virtual int app_sp_Deleteapp_gender(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Deleteapp_gender", idParameter);
        }
    
        public virtual int app_sp_Deleteapp_home_type(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Deleteapp_home_type", idParameter);
        }
    
        public virtual int app_sp_Deleteapp_kin_detail(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Deleteapp_kin_detail", idParameter);
        }
    
        public virtual int app_sp_Deleteapp_kin_type(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Deleteapp_kin_type", idParameter);
        }
    
        public virtual int app_sp_Deleteapp_occupation(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Deleteapp_occupation", idParameter);
        }
    
        public virtual int app_sp_Deleteapp_rel_office(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Deleteapp_rel_office", idParameter);
        }
    
        public virtual int app_sp_Deletesysdiagram(Nullable<int> diagram_id)
        {
            var diagram_idParameter = diagram_id.HasValue ?
                new ObjectParameter("diagram_id", diagram_id) :
                new ObjectParameter("diagram_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Deletesysdiagram", diagram_idParameter);
        }
    
        public virtual ObjectResult<app_sp_Getapp_age_cate_Result> app_sp_Getapp_age_cate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_age_cate_Result>("app_sp_Getapp_age_cate");
        }
    
        public virtual ObjectResult<app_sp_Getapp_age_cateDetails_Result> app_sp_Getapp_age_cateDetails(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_age_cateDetails_Result>("app_sp_Getapp_age_cateDetails", idParameter);
        }
    
        public virtual ObjectResult<app_sp_Getapp_bran_type_Result> app_sp_Getapp_bran_type()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_bran_type_Result>("app_sp_Getapp_bran_type");
        }
    
        public virtual ObjectResult<app_sp_Getapp_bran_typeDetails_Result> app_sp_Getapp_bran_typeDetails(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_bran_typeDetails_Result>("app_sp_Getapp_bran_typeDetails", idParameter);
        }
    
        public virtual ObjectResult<app_sp_Getapp_branch_Result> app_sp_Getapp_branch()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_branch_Result>("app_sp_Getapp_branch");
        }
    
        public virtual ObjectResult<app_sp_Getapp_branchDetails_Result> app_sp_Getapp_branchDetails(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_branchDetails_Result>("app_sp_Getapp_branchDetails", idParameter);
        }
    
        public virtual ObjectResult<app_sp_Getapp_countrieDetails_Result> app_sp_Getapp_countrieDetails(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_countrieDetails_Result>("app_sp_Getapp_countrieDetails", idParameter);
        }
    
        public virtual ObjectResult<app_sp_Getapp_countries_Result> app_sp_Getapp_countries()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_countries_Result>("app_sp_Getapp_countries");
        }
    
        public virtual ObjectResult<app_sp_Getapp_cus_contact_Result> app_sp_Getapp_cus_contact()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_cus_contact_Result>("app_sp_Getapp_cus_contact");
        }
    
        public virtual ObjectResult<app_sp_Getapp_cus_contactDetails_Result> app_sp_Getapp_cus_contactDetails(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_cus_contactDetails_Result>("app_sp_Getapp_cus_contactDetails", idParameter);
        }
    
        public virtual ObjectResult<app_sp_Getapp_cus_doc_Result> app_sp_Getapp_cus_doc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_cus_doc_Result>("app_sp_Getapp_cus_doc");
        }
    
        public virtual ObjectResult<app_sp_Getapp_cus_docDetails_Result> app_sp_Getapp_cus_docDetails(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_cus_docDetails_Result>("app_sp_Getapp_cus_docDetails", idParameter);
        }
    
        public virtual ObjectResult<app_sp_Getapp_cus_main_Result> app_sp_Getapp_cus_main()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_cus_main_Result>("app_sp_Getapp_cus_main");
        }
    
        public virtual ObjectResult<app_sp_Getapp_cus_mainDetails_Result> app_sp_Getapp_cus_mainDetails(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_cus_mainDetails_Result>("app_sp_Getapp_cus_mainDetails", idParameter);
        }
    
        public virtual ObjectResult<app_sp_Getapp_cus_other_info_Result> app_sp_Getapp_cus_other_info()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_cus_other_info_Result>("app_sp_Getapp_cus_other_info");
        }
    
        public virtual ObjectResult<app_sp_Getapp_cus_other_infoDetails_Result> app_sp_Getapp_cus_other_infoDetails(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_cus_other_infoDetails_Result>("app_sp_Getapp_cus_other_infoDetails", idParameter);
        }
    
        public virtual ObjectResult<app_sp_Getapp_cus_type_Result> app_sp_Getapp_cus_type()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_cus_type_Result>("app_sp_Getapp_cus_type");
        }
    
        public virtual ObjectResult<app_sp_Getapp_cus_typeDetails_Result> app_sp_Getapp_cus_typeDetails(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_cus_typeDetails_Result>("app_sp_Getapp_cus_typeDetails", idParameter);
        }
    
        public virtual ObjectResult<app_sp_Getapp_doc_type_Result> app_sp_Getapp_doc_type()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_doc_type_Result>("app_sp_Getapp_doc_type");
        }
    
        public virtual ObjectResult<app_sp_Getapp_doc_typeDetails_Result> app_sp_Getapp_doc_typeDetails(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_doc_typeDetails_Result>("app_sp_Getapp_doc_typeDetails", idParameter);
        }
    
        public virtual ObjectResult<app_sp_Getapp_gender_Result> app_sp_Getapp_gender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_gender_Result>("app_sp_Getapp_gender");
        }
    
        public virtual ObjectResult<app_sp_Getapp_genderDetails_Result> app_sp_Getapp_genderDetails(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_genderDetails_Result>("app_sp_Getapp_genderDetails", idParameter);
        }
    
        public virtual ObjectResult<app_sp_Getapp_home_type_Result> app_sp_Getapp_home_type()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_home_type_Result>("app_sp_Getapp_home_type");
        }
    
        public virtual ObjectResult<app_sp_Getapp_home_typeDetails_Result> app_sp_Getapp_home_typeDetails(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_home_typeDetails_Result>("app_sp_Getapp_home_typeDetails", idParameter);
        }
    
        public virtual ObjectResult<app_sp_Getapp_kin_detailDetails_Result> app_sp_Getapp_kin_detailDetails(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_kin_detailDetails_Result>("app_sp_Getapp_kin_detailDetails", idParameter);
        }
    
        public virtual ObjectResult<app_sp_Getapp_kin_details_Result> app_sp_Getapp_kin_details()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_kin_details_Result>("app_sp_Getapp_kin_details");
        }
    
        public virtual ObjectResult<app_sp_Getapp_kin_type_Result> app_sp_Getapp_kin_type()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_kin_type_Result>("app_sp_Getapp_kin_type");
        }
    
        public virtual ObjectResult<app_sp_Getapp_kin_typeDetails_Result> app_sp_Getapp_kin_typeDetails(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_kin_typeDetails_Result>("app_sp_Getapp_kin_typeDetails", idParameter);
        }
    
        public virtual ObjectResult<app_sp_Getapp_occupation_Result> app_sp_Getapp_occupation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_occupation_Result>("app_sp_Getapp_occupation");
        }
    
        public virtual ObjectResult<app_sp_Getapp_occupationDetails_Result> app_sp_Getapp_occupationDetails(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_occupationDetails_Result>("app_sp_Getapp_occupationDetails", idParameter);
        }
    
        public virtual ObjectResult<app_sp_Getapp_rel_office_Result> app_sp_Getapp_rel_office()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_rel_office_Result>("app_sp_Getapp_rel_office");
        }
    
        public virtual ObjectResult<app_sp_Getapp_rel_officeDetails_Result> app_sp_Getapp_rel_officeDetails(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getapp_rel_officeDetails_Result>("app_sp_Getapp_rel_officeDetails", idParameter);
        }
    
        public virtual ObjectResult<app_sp_GetsysdiagramDetails_Result> app_sp_GetsysdiagramDetails(Nullable<int> diagram_id)
        {
            var diagram_idParameter = diagram_id.HasValue ?
                new ObjectParameter("diagram_id", diagram_id) :
                new ObjectParameter("diagram_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_GetsysdiagramDetails_Result>("app_sp_GetsysdiagramDetails", diagram_idParameter);
        }
    
        public virtual ObjectResult<app_sp_Getsysdiagrams_Result> app_sp_Getsysdiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<app_sp_Getsysdiagrams_Result>("app_sp_Getsysdiagrams");
        }
    
        public virtual int app_sp_Insertapp_age_cate(string age_code, string name_of_cat, ObjectParameter id)
        {
            var age_codeParameter = age_code != null ?
                new ObjectParameter("age_code", age_code) :
                new ObjectParameter("age_code", typeof(string));
    
            var name_of_catParameter = name_of_cat != null ?
                new ObjectParameter("name_of_cat", name_of_cat) :
                new ObjectParameter("name_of_cat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Insertapp_age_cate", age_codeParameter, name_of_catParameter, id);
        }
    
        public virtual int app_sp_Insertapp_bran_type(Nullable<int> bran_type_code, string name, ObjectParameter id)
        {
            var bran_type_codeParameter = bran_type_code.HasValue ?
                new ObjectParameter("bran_type_code", bran_type_code) :
                new ObjectParameter("bran_type_code", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Insertapp_bran_type", bran_type_codeParameter, nameParameter, id);
        }
    
        public virtual int app_sp_Insertapp_branch(Nullable<int> bran_code, string branch_name, Nullable<int> bran_type_code, string address1, string address2, string state, string zip, string assets, ObjectParameter id)
        {
            var bran_codeParameter = bran_code.HasValue ?
                new ObjectParameter("bran_code", bran_code) :
                new ObjectParameter("bran_code", typeof(int));
    
            var branch_nameParameter = branch_name != null ?
                new ObjectParameter("branch_name", branch_name) :
                new ObjectParameter("branch_name", typeof(string));
    
            var bran_type_codeParameter = bran_type_code.HasValue ?
                new ObjectParameter("bran_type_code", bran_type_code) :
                new ObjectParameter("bran_type_code", typeof(int));
    
            var address1Parameter = address1 != null ?
                new ObjectParameter("address1", address1) :
                new ObjectParameter("address1", typeof(string));
    
            var address2Parameter = address2 != null ?
                new ObjectParameter("address2", address2) :
                new ObjectParameter("address2", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var zipParameter = zip != null ?
                new ObjectParameter("zip", zip) :
                new ObjectParameter("zip", typeof(string));
    
            var assetsParameter = assets != null ?
                new ObjectParameter("assets", assets) :
                new ObjectParameter("assets", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Insertapp_branch", bran_codeParameter, branch_nameParameter, bran_type_codeParameter, address1Parameter, address2Parameter, stateParameter, zipParameter, assetsParameter, id);
        }
    
        public virtual int app_sp_Insertapp_countrie(string name, ObjectParameter id)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Insertapp_countrie", nameParameter, id);
        }
    
        public virtual int app_sp_Insertapp_cus_contact(Nullable<int> contact_code, string tele_number, string fax, string email, string address1, string address2, string city, string state, string zip, string brief_location, string gps_cordinates, Nullable<int> country_code, string tele_number2, ObjectParameter id)
        {
            var contact_codeParameter = contact_code.HasValue ?
                new ObjectParameter("contact_code", contact_code) :
                new ObjectParameter("contact_code", typeof(int));
    
            var tele_numberParameter = tele_number != null ?
                new ObjectParameter("tele_number", tele_number) :
                new ObjectParameter("tele_number", typeof(string));
    
            var faxParameter = fax != null ?
                new ObjectParameter("fax", fax) :
                new ObjectParameter("fax", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var address1Parameter = address1 != null ?
                new ObjectParameter("address1", address1) :
                new ObjectParameter("address1", typeof(string));
    
            var address2Parameter = address2 != null ?
                new ObjectParameter("address2", address2) :
                new ObjectParameter("address2", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var zipParameter = zip != null ?
                new ObjectParameter("zip", zip) :
                new ObjectParameter("zip", typeof(string));
    
            var brief_locationParameter = brief_location != null ?
                new ObjectParameter("brief_location", brief_location) :
                new ObjectParameter("brief_location", typeof(string));
    
            var gps_cordinatesParameter = gps_cordinates != null ?
                new ObjectParameter("gps_cordinates", gps_cordinates) :
                new ObjectParameter("gps_cordinates", typeof(string));
    
            var country_codeParameter = country_code.HasValue ?
                new ObjectParameter("country_code", country_code) :
                new ObjectParameter("country_code", typeof(int));
    
            var tele_number2Parameter = tele_number2 != null ?
                new ObjectParameter("tele_number2", tele_number2) :
                new ObjectParameter("tele_number2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Insertapp_cus_contact", contact_codeParameter, tele_numberParameter, faxParameter, emailParameter, address1Parameter, address2Parameter, cityParameter, stateParameter, zipParameter, brief_locationParameter, gps_cordinatesParameter, country_codeParameter, tele_number2Parameter, id);
        }
    
        public virtual int app_sp_Insertapp_cus_doc(Nullable<int> cus_doc_code, string cus_doc_name, string cus_doc_url, Nullable<int> cus_doc_type_code, string createdby, string modifiedby, string deletedby, Nullable<System.DateTime> created_date, Nullable<System.DateTime> modified_date, Nullable<System.DateTime> deleted_date, ObjectParameter id)
        {
            var cus_doc_codeParameter = cus_doc_code.HasValue ?
                new ObjectParameter("cus_doc_code", cus_doc_code) :
                new ObjectParameter("cus_doc_code", typeof(int));
    
            var cus_doc_nameParameter = cus_doc_name != null ?
                new ObjectParameter("cus_doc_name", cus_doc_name) :
                new ObjectParameter("cus_doc_name", typeof(string));
    
            var cus_doc_urlParameter = cus_doc_url != null ?
                new ObjectParameter("cus_doc_url", cus_doc_url) :
                new ObjectParameter("cus_doc_url", typeof(string));
    
            var cus_doc_type_codeParameter = cus_doc_type_code.HasValue ?
                new ObjectParameter("cus_doc_type_code", cus_doc_type_code) :
                new ObjectParameter("cus_doc_type_code", typeof(int));
    
            var createdbyParameter = createdby != null ?
                new ObjectParameter("createdby", createdby) :
                new ObjectParameter("createdby", typeof(string));
    
            var modifiedbyParameter = modifiedby != null ?
                new ObjectParameter("modifiedby", modifiedby) :
                new ObjectParameter("modifiedby", typeof(string));
    
            var deletedbyParameter = deletedby != null ?
                new ObjectParameter("deletedby", deletedby) :
                new ObjectParameter("deletedby", typeof(string));
    
            var created_dateParameter = created_date.HasValue ?
                new ObjectParameter("created_date", created_date) :
                new ObjectParameter("created_date", typeof(System.DateTime));
    
            var modified_dateParameter = modified_date.HasValue ?
                new ObjectParameter("modified_date", modified_date) :
                new ObjectParameter("modified_date", typeof(System.DateTime));
    
            var deleted_dateParameter = deleted_date.HasValue ?
                new ObjectParameter("deleted_date", deleted_date) :
                new ObjectParameter("deleted_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Insertapp_cus_doc", cus_doc_codeParameter, cus_doc_nameParameter, cus_doc_urlParameter, cus_doc_type_codeParameter, createdbyParameter, modifiedbyParameter, deletedbyParameter, created_dateParameter, modified_dateParameter, deleted_dateParameter, id);
        }
    
        public virtual int app_sp_Insertapp_cus_main(Nullable<int> cus_type_code, Nullable<int> bran_code, Nullable<int> rel_off_code, string title, string firstname, string lastname, string middlename, Nullable<System.DateTime> dob, Nullable<int> age_cat_type_code, Nullable<int> gender, Nullable<int> occupation_code, string cus_code, string img_url, string sign_img_url, string marital_status, Nullable<int> child_num, Nullable<int> home_type_code, Nullable<System.DateTime> cus_since, Nullable<int> cus_other_code, Nullable<int> kin_details_code, Nullable<int> contact_code, Nullable<int> cus_doc_code, Nullable<decimal> credit_limit, string created_by, string modified_by, string deleted_by, Nullable<System.DateTime> created_date, Nullable<System.DateTime> modified_date, Nullable<System.DateTime> deleted_date, string full_name, string status, Nullable<int> citizenship, ObjectParameter id)
        {
            var cus_type_codeParameter = cus_type_code.HasValue ?
                new ObjectParameter("cus_type_code", cus_type_code) :
                new ObjectParameter("cus_type_code", typeof(int));
    
            var bran_codeParameter = bran_code.HasValue ?
                new ObjectParameter("bran_code", bran_code) :
                new ObjectParameter("bran_code", typeof(int));
    
            var rel_off_codeParameter = rel_off_code.HasValue ?
                new ObjectParameter("rel_off_code", rel_off_code) :
                new ObjectParameter("rel_off_code", typeof(int));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var middlenameParameter = middlename != null ?
                new ObjectParameter("middlename", middlename) :
                new ObjectParameter("middlename", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var age_cat_type_codeParameter = age_cat_type_code.HasValue ?
                new ObjectParameter("age_cat_type_code", age_cat_type_code) :
                new ObjectParameter("age_cat_type_code", typeof(int));
    
            var genderParameter = gender.HasValue ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(int));
    
            var occupation_codeParameter = occupation_code.HasValue ?
                new ObjectParameter("occupation_code", occupation_code) :
                new ObjectParameter("occupation_code", typeof(int));
    
            var cus_codeParameter = cus_code != null ?
                new ObjectParameter("cus_code", cus_code) :
                new ObjectParameter("cus_code", typeof(string));
    
            var img_urlParameter = img_url != null ?
                new ObjectParameter("img_url", img_url) :
                new ObjectParameter("img_url", typeof(string));
    
            var sign_img_urlParameter = sign_img_url != null ?
                new ObjectParameter("sign_img_url", sign_img_url) :
                new ObjectParameter("sign_img_url", typeof(string));
    
            var marital_statusParameter = marital_status != null ?
                new ObjectParameter("marital_status", marital_status) :
                new ObjectParameter("marital_status", typeof(string));
    
            var child_numParameter = child_num.HasValue ?
                new ObjectParameter("child_num", child_num) :
                new ObjectParameter("child_num", typeof(int));
    
            var home_type_codeParameter = home_type_code.HasValue ?
                new ObjectParameter("home_type_code", home_type_code) :
                new ObjectParameter("home_type_code", typeof(int));
    
            var cus_sinceParameter = cus_since.HasValue ?
                new ObjectParameter("cus_since", cus_since) :
                new ObjectParameter("cus_since", typeof(System.DateTime));
    
            var cus_other_codeParameter = cus_other_code.HasValue ?
                new ObjectParameter("cus_other_code", cus_other_code) :
                new ObjectParameter("cus_other_code", typeof(int));
    
            var kin_details_codeParameter = kin_details_code.HasValue ?
                new ObjectParameter("kin_details_code", kin_details_code) :
                new ObjectParameter("kin_details_code", typeof(int));
    
            var contact_codeParameter = contact_code.HasValue ?
                new ObjectParameter("contact_code", contact_code) :
                new ObjectParameter("contact_code", typeof(int));
    
            var cus_doc_codeParameter = cus_doc_code.HasValue ?
                new ObjectParameter("cus_doc_code", cus_doc_code) :
                new ObjectParameter("cus_doc_code", typeof(int));
    
            var credit_limitParameter = credit_limit.HasValue ?
                new ObjectParameter("credit_limit", credit_limit) :
                new ObjectParameter("credit_limit", typeof(decimal));
    
            var created_byParameter = created_by != null ?
                new ObjectParameter("created_by", created_by) :
                new ObjectParameter("created_by", typeof(string));
    
            var modified_byParameter = modified_by != null ?
                new ObjectParameter("modified_by", modified_by) :
                new ObjectParameter("modified_by", typeof(string));
    
            var deleted_byParameter = deleted_by != null ?
                new ObjectParameter("deleted_by", deleted_by) :
                new ObjectParameter("deleted_by", typeof(string));
    
            var created_dateParameter = created_date.HasValue ?
                new ObjectParameter("created_date", created_date) :
                new ObjectParameter("created_date", typeof(System.DateTime));
    
            var modified_dateParameter = modified_date.HasValue ?
                new ObjectParameter("modified_date", modified_date) :
                new ObjectParameter("modified_date", typeof(System.DateTime));
    
            var deleted_dateParameter = deleted_date.HasValue ?
                new ObjectParameter("deleted_date", deleted_date) :
                new ObjectParameter("deleted_date", typeof(System.DateTime));
    
            var full_nameParameter = full_name != null ?
                new ObjectParameter("full_name", full_name) :
                new ObjectParameter("full_name", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var citizenshipParameter = citizenship.HasValue ?
                new ObjectParameter("citizenship", citizenship) :
                new ObjectParameter("citizenship", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Insertapp_cus_main", cus_type_codeParameter, bran_codeParameter, rel_off_codeParameter, titleParameter, firstnameParameter, lastnameParameter, middlenameParameter, dobParameter, age_cat_type_codeParameter, genderParameter, occupation_codeParameter, cus_codeParameter, img_urlParameter, sign_img_urlParameter, marital_statusParameter, child_numParameter, home_type_codeParameter, cus_sinceParameter, cus_other_codeParameter, kin_details_codeParameter, contact_codeParameter, cus_doc_codeParameter, credit_limitParameter, created_byParameter, modified_byParameter, deleted_byParameter, created_dateParameter, modified_dateParameter, deleted_dateParameter, full_nameParameter, statusParameter, citizenshipParameter, id);
        }
    
        public virtual int app_sp_Insertapp_cus_other_info(string cus_other_code, string verification_id, string ssn, string tax_number, string security_group, string tin_number, ObjectParameter id)
        {
            var cus_other_codeParameter = cus_other_code != null ?
                new ObjectParameter("cus_other_code", cus_other_code) :
                new ObjectParameter("cus_other_code", typeof(string));
    
            var verification_idParameter = verification_id != null ?
                new ObjectParameter("verification_id", verification_id) :
                new ObjectParameter("verification_id", typeof(string));
    
            var ssnParameter = ssn != null ?
                new ObjectParameter("ssn", ssn) :
                new ObjectParameter("ssn", typeof(string));
    
            var tax_numberParameter = tax_number != null ?
                new ObjectParameter("tax_number", tax_number) :
                new ObjectParameter("tax_number", typeof(string));
    
            var security_groupParameter = security_group != null ?
                new ObjectParameter("security_group", security_group) :
                new ObjectParameter("security_group", typeof(string));
    
            var tin_numberParameter = tin_number != null ?
                new ObjectParameter("tin_number", tin_number) :
                new ObjectParameter("tin_number", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Insertapp_cus_other_info", cus_other_codeParameter, verification_idParameter, ssnParameter, tax_numberParameter, security_groupParameter, tin_numberParameter, id);
        }
    
        public virtual int app_sp_Insertapp_cus_type(string cus_type_code, string type_name, string status, ObjectParameter id)
        {
            var cus_type_codeParameter = cus_type_code != null ?
                new ObjectParameter("cus_type_code", cus_type_code) :
                new ObjectParameter("cus_type_code", typeof(string));
    
            var type_nameParameter = type_name != null ?
                new ObjectParameter("type_name", type_name) :
                new ObjectParameter("type_name", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Insertapp_cus_type", cus_type_codeParameter, type_nameParameter, statusParameter, id);
        }
    
        public virtual int app_sp_Insertapp_doc_type(Nullable<int> doc_type_code, string name, string type, ObjectParameter id)
        {
            var doc_type_codeParameter = doc_type_code.HasValue ?
                new ObjectParameter("doc_type_code", doc_type_code) :
                new ObjectParameter("doc_type_code", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Insertapp_doc_type", doc_type_codeParameter, nameParameter, typeParameter, id);
        }
    
        public virtual int app_sp_Insertapp_gender(string gender_code, string sex, ObjectParameter id)
        {
            var gender_codeParameter = gender_code != null ?
                new ObjectParameter("gender_code", gender_code) :
                new ObjectParameter("gender_code", typeof(string));
    
            var sexParameter = sex != null ?
                new ObjectParameter("sex", sex) :
                new ObjectParameter("sex", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Insertapp_gender", gender_codeParameter, sexParameter, id);
        }
    
        public virtual int app_sp_Insertapp_home_type(string home_code, string type_name, ObjectParameter id)
        {
            var home_codeParameter = home_code != null ?
                new ObjectParameter("home_code", home_code) :
                new ObjectParameter("home_code", typeof(string));
    
            var type_nameParameter = type_name != null ?
                new ObjectParameter("type_name", type_name) :
                new ObjectParameter("type_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Insertapp_home_type", home_codeParameter, type_nameParameter, id);
        }
    
        public virtual int app_sp_Insertapp_kin_detail(Nullable<int> kin_type_code, string kin_details_code, string full_name, string firstname, string lastname, string middle, string relationship, string tele_num_rel, string email, string address1, string address2, string zip, string city, string state, ObjectParameter id)
        {
            var kin_type_codeParameter = kin_type_code.HasValue ?
                new ObjectParameter("kin_type_code", kin_type_code) :
                new ObjectParameter("kin_type_code", typeof(int));
    
            var kin_details_codeParameter = kin_details_code != null ?
                new ObjectParameter("kin_details_code", kin_details_code) :
                new ObjectParameter("kin_details_code", typeof(string));
    
            var full_nameParameter = full_name != null ?
                new ObjectParameter("full_name", full_name) :
                new ObjectParameter("full_name", typeof(string));
    
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var middleParameter = middle != null ?
                new ObjectParameter("middle", middle) :
                new ObjectParameter("middle", typeof(string));
    
            var relationshipParameter = relationship != null ?
                new ObjectParameter("relationship", relationship) :
                new ObjectParameter("relationship", typeof(string));
    
            var tele_num_relParameter = tele_num_rel != null ?
                new ObjectParameter("tele_num_rel", tele_num_rel) :
                new ObjectParameter("tele_num_rel", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var address1Parameter = address1 != null ?
                new ObjectParameter("address1", address1) :
                new ObjectParameter("address1", typeof(string));
    
            var address2Parameter = address2 != null ?
                new ObjectParameter("address2", address2) :
                new ObjectParameter("address2", typeof(string));
    
            var zipParameter = zip != null ?
                new ObjectParameter("zip", zip) :
                new ObjectParameter("zip", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Insertapp_kin_detail", kin_type_codeParameter, kin_details_codeParameter, full_nameParameter, firstnameParameter, lastnameParameter, middleParameter, relationshipParameter, tele_num_relParameter, emailParameter, address1Parameter, address2Parameter, zipParameter, cityParameter, stateParameter, id);
        }
    
        public virtual int app_sp_Insertapp_kin_type(Nullable<int> kin_type_code, string kin_type_name, ObjectParameter id)
        {
            var kin_type_codeParameter = kin_type_code.HasValue ?
                new ObjectParameter("kin_type_code", kin_type_code) :
                new ObjectParameter("kin_type_code", typeof(int));
    
            var kin_type_nameParameter = kin_type_name != null ?
                new ObjectParameter("kin_type_name", kin_type_name) :
                new ObjectParameter("kin_type_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Insertapp_kin_type", kin_type_codeParameter, kin_type_nameParameter, id);
        }
    
        public virtual int app_sp_Insertapp_occupation(string occ_code, string name, ObjectParameter id)
        {
            var occ_codeParameter = occ_code != null ?
                new ObjectParameter("occ_code", occ_code) :
                new ObjectParameter("occ_code", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Insertapp_occupation", occ_codeParameter, nameParameter, id);
        }
    
        public virtual int app_sp_Insertapp_rel_office(string rel_code, string full_name, string firstname, string lastname, string middlename, string status, string bran_code, ObjectParameter id)
        {
            var rel_codeParameter = rel_code != null ?
                new ObjectParameter("rel_code", rel_code) :
                new ObjectParameter("rel_code", typeof(string));
    
            var full_nameParameter = full_name != null ?
                new ObjectParameter("full_name", full_name) :
                new ObjectParameter("full_name", typeof(string));
    
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var middlenameParameter = middlename != null ?
                new ObjectParameter("middlename", middlename) :
                new ObjectParameter("middlename", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var bran_codeParameter = bran_code != null ?
                new ObjectParameter("bran_code", bran_code) :
                new ObjectParameter("bran_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Insertapp_rel_office", rel_codeParameter, full_nameParameter, firstnameParameter, lastnameParameter, middlenameParameter, statusParameter, bran_codeParameter, id);
        }
    
        public virtual int app_sp_Updateapp_age_cate(Nullable<int> id, string age_code, string name_of_cat)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var age_codeParameter = age_code != null ?
                new ObjectParameter("age_code", age_code) :
                new ObjectParameter("age_code", typeof(string));
    
            var name_of_catParameter = name_of_cat != null ?
                new ObjectParameter("name_of_cat", name_of_cat) :
                new ObjectParameter("name_of_cat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Updateapp_age_cate", idParameter, age_codeParameter, name_of_catParameter);
        }
    
        public virtual int app_sp_Updateapp_bran_type(Nullable<int> id, Nullable<int> bran_type_code, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var bran_type_codeParameter = bran_type_code.HasValue ?
                new ObjectParameter("bran_type_code", bran_type_code) :
                new ObjectParameter("bran_type_code", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Updateapp_bran_type", idParameter, bran_type_codeParameter, nameParameter);
        }
    
        public virtual int app_sp_Updateapp_branch(Nullable<int> id, Nullable<int> bran_code, string branch_name, Nullable<int> bran_type_code, string address1, string address2, string state, string zip, string assets)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var bran_codeParameter = bran_code.HasValue ?
                new ObjectParameter("bran_code", bran_code) :
                new ObjectParameter("bran_code", typeof(int));
    
            var branch_nameParameter = branch_name != null ?
                new ObjectParameter("branch_name", branch_name) :
                new ObjectParameter("branch_name", typeof(string));
    
            var bran_type_codeParameter = bran_type_code.HasValue ?
                new ObjectParameter("bran_type_code", bran_type_code) :
                new ObjectParameter("bran_type_code", typeof(int));
    
            var address1Parameter = address1 != null ?
                new ObjectParameter("address1", address1) :
                new ObjectParameter("address1", typeof(string));
    
            var address2Parameter = address2 != null ?
                new ObjectParameter("address2", address2) :
                new ObjectParameter("address2", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var zipParameter = zip != null ?
                new ObjectParameter("zip", zip) :
                new ObjectParameter("zip", typeof(string));
    
            var assetsParameter = assets != null ?
                new ObjectParameter("assets", assets) :
                new ObjectParameter("assets", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Updateapp_branch", idParameter, bran_codeParameter, branch_nameParameter, bran_type_codeParameter, address1Parameter, address2Parameter, stateParameter, zipParameter, assetsParameter);
        }
    
        public virtual int app_sp_Updateapp_countrie(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Updateapp_countrie", idParameter, nameParameter);
        }
    
        public virtual int app_sp_Updateapp_cus_contact(Nullable<int> id, Nullable<int> contact_code, string tele_number, string fax, string email, string address1, string address2, string city, string state, string zip, string brief_location, string gps_cordinates, Nullable<int> country_code, string tele_number2)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var contact_codeParameter = contact_code.HasValue ?
                new ObjectParameter("contact_code", contact_code) :
                new ObjectParameter("contact_code", typeof(int));
    
            var tele_numberParameter = tele_number != null ?
                new ObjectParameter("tele_number", tele_number) :
                new ObjectParameter("tele_number", typeof(string));
    
            var faxParameter = fax != null ?
                new ObjectParameter("fax", fax) :
                new ObjectParameter("fax", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var address1Parameter = address1 != null ?
                new ObjectParameter("address1", address1) :
                new ObjectParameter("address1", typeof(string));
    
            var address2Parameter = address2 != null ?
                new ObjectParameter("address2", address2) :
                new ObjectParameter("address2", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var zipParameter = zip != null ?
                new ObjectParameter("zip", zip) :
                new ObjectParameter("zip", typeof(string));
    
            var brief_locationParameter = brief_location != null ?
                new ObjectParameter("brief_location", brief_location) :
                new ObjectParameter("brief_location", typeof(string));
    
            var gps_cordinatesParameter = gps_cordinates != null ?
                new ObjectParameter("gps_cordinates", gps_cordinates) :
                new ObjectParameter("gps_cordinates", typeof(string));
    
            var country_codeParameter = country_code.HasValue ?
                new ObjectParameter("country_code", country_code) :
                new ObjectParameter("country_code", typeof(int));
    
            var tele_number2Parameter = tele_number2 != null ?
                new ObjectParameter("tele_number2", tele_number2) :
                new ObjectParameter("tele_number2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Updateapp_cus_contact", idParameter, contact_codeParameter, tele_numberParameter, faxParameter, emailParameter, address1Parameter, address2Parameter, cityParameter, stateParameter, zipParameter, brief_locationParameter, gps_cordinatesParameter, country_codeParameter, tele_number2Parameter);
        }
    
        public virtual int app_sp_Updateapp_cus_doc(Nullable<int> id, Nullable<int> cus_doc_code, string cus_doc_name, string cus_doc_url, Nullable<int> cus_doc_type_code, string createdby, string modifiedby, string deletedby, Nullable<System.DateTime> created_date, Nullable<System.DateTime> modified_date, Nullable<System.DateTime> deleted_date)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var cus_doc_codeParameter = cus_doc_code.HasValue ?
                new ObjectParameter("cus_doc_code", cus_doc_code) :
                new ObjectParameter("cus_doc_code", typeof(int));
    
            var cus_doc_nameParameter = cus_doc_name != null ?
                new ObjectParameter("cus_doc_name", cus_doc_name) :
                new ObjectParameter("cus_doc_name", typeof(string));
    
            var cus_doc_urlParameter = cus_doc_url != null ?
                new ObjectParameter("cus_doc_url", cus_doc_url) :
                new ObjectParameter("cus_doc_url", typeof(string));
    
            var cus_doc_type_codeParameter = cus_doc_type_code.HasValue ?
                new ObjectParameter("cus_doc_type_code", cus_doc_type_code) :
                new ObjectParameter("cus_doc_type_code", typeof(int));
    
            var createdbyParameter = createdby != null ?
                new ObjectParameter("createdby", createdby) :
                new ObjectParameter("createdby", typeof(string));
    
            var modifiedbyParameter = modifiedby != null ?
                new ObjectParameter("modifiedby", modifiedby) :
                new ObjectParameter("modifiedby", typeof(string));
    
            var deletedbyParameter = deletedby != null ?
                new ObjectParameter("deletedby", deletedby) :
                new ObjectParameter("deletedby", typeof(string));
    
            var created_dateParameter = created_date.HasValue ?
                new ObjectParameter("created_date", created_date) :
                new ObjectParameter("created_date", typeof(System.DateTime));
    
            var modified_dateParameter = modified_date.HasValue ?
                new ObjectParameter("modified_date", modified_date) :
                new ObjectParameter("modified_date", typeof(System.DateTime));
    
            var deleted_dateParameter = deleted_date.HasValue ?
                new ObjectParameter("deleted_date", deleted_date) :
                new ObjectParameter("deleted_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Updateapp_cus_doc", idParameter, cus_doc_codeParameter, cus_doc_nameParameter, cus_doc_urlParameter, cus_doc_type_codeParameter, createdbyParameter, modifiedbyParameter, deletedbyParameter, created_dateParameter, modified_dateParameter, deleted_dateParameter);
        }
    
        public virtual int app_sp_Updateapp_cus_main(Nullable<int> id, Nullable<int> cus_type_code, Nullable<int> bran_code, Nullable<int> rel_off_code, string title, string firstname, string lastname, string middlename, Nullable<System.DateTime> dob, Nullable<int> age_cat_type_code, Nullable<int> gender, Nullable<int> occupation_code, string cus_code, string img_url, string sign_img_url, string marital_status, Nullable<int> child_num, Nullable<int> home_type_code, Nullable<System.DateTime> cus_since, Nullable<int> cus_other_code, Nullable<int> kin_details_code, Nullable<int> contact_code, Nullable<int> cus_doc_code, Nullable<decimal> credit_limit, string created_by, string modified_by, string deleted_by, Nullable<System.DateTime> created_date, Nullable<System.DateTime> modified_date, Nullable<System.DateTime> deleted_date, string full_name, string status, Nullable<int> citizenship)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var cus_type_codeParameter = cus_type_code.HasValue ?
                new ObjectParameter("cus_type_code", cus_type_code) :
                new ObjectParameter("cus_type_code", typeof(int));
    
            var bran_codeParameter = bran_code.HasValue ?
                new ObjectParameter("bran_code", bran_code) :
                new ObjectParameter("bran_code", typeof(int));
    
            var rel_off_codeParameter = rel_off_code.HasValue ?
                new ObjectParameter("rel_off_code", rel_off_code) :
                new ObjectParameter("rel_off_code", typeof(int));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var middlenameParameter = middlename != null ?
                new ObjectParameter("middlename", middlename) :
                new ObjectParameter("middlename", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var age_cat_type_codeParameter = age_cat_type_code.HasValue ?
                new ObjectParameter("age_cat_type_code", age_cat_type_code) :
                new ObjectParameter("age_cat_type_code", typeof(int));
    
            var genderParameter = gender.HasValue ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(int));
    
            var occupation_codeParameter = occupation_code.HasValue ?
                new ObjectParameter("occupation_code", occupation_code) :
                new ObjectParameter("occupation_code", typeof(int));
    
            var cus_codeParameter = cus_code != null ?
                new ObjectParameter("cus_code", cus_code) :
                new ObjectParameter("cus_code", typeof(string));
    
            var img_urlParameter = img_url != null ?
                new ObjectParameter("img_url", img_url) :
                new ObjectParameter("img_url", typeof(string));
    
            var sign_img_urlParameter = sign_img_url != null ?
                new ObjectParameter("sign_img_url", sign_img_url) :
                new ObjectParameter("sign_img_url", typeof(string));
    
            var marital_statusParameter = marital_status != null ?
                new ObjectParameter("marital_status", marital_status) :
                new ObjectParameter("marital_status", typeof(string));
    
            var child_numParameter = child_num.HasValue ?
                new ObjectParameter("child_num", child_num) :
                new ObjectParameter("child_num", typeof(int));
    
            var home_type_codeParameter = home_type_code.HasValue ?
                new ObjectParameter("home_type_code", home_type_code) :
                new ObjectParameter("home_type_code", typeof(int));
    
            var cus_sinceParameter = cus_since.HasValue ?
                new ObjectParameter("cus_since", cus_since) :
                new ObjectParameter("cus_since", typeof(System.DateTime));
    
            var cus_other_codeParameter = cus_other_code.HasValue ?
                new ObjectParameter("cus_other_code", cus_other_code) :
                new ObjectParameter("cus_other_code", typeof(int));
    
            var kin_details_codeParameter = kin_details_code.HasValue ?
                new ObjectParameter("kin_details_code", kin_details_code) :
                new ObjectParameter("kin_details_code", typeof(int));
    
            var contact_codeParameter = contact_code.HasValue ?
                new ObjectParameter("contact_code", contact_code) :
                new ObjectParameter("contact_code", typeof(int));
    
            var cus_doc_codeParameter = cus_doc_code.HasValue ?
                new ObjectParameter("cus_doc_code", cus_doc_code) :
                new ObjectParameter("cus_doc_code", typeof(int));
    
            var credit_limitParameter = credit_limit.HasValue ?
                new ObjectParameter("credit_limit", credit_limit) :
                new ObjectParameter("credit_limit", typeof(decimal));
    
            var created_byParameter = created_by != null ?
                new ObjectParameter("created_by", created_by) :
                new ObjectParameter("created_by", typeof(string));
    
            var modified_byParameter = modified_by != null ?
                new ObjectParameter("modified_by", modified_by) :
                new ObjectParameter("modified_by", typeof(string));
    
            var deleted_byParameter = deleted_by != null ?
                new ObjectParameter("deleted_by", deleted_by) :
                new ObjectParameter("deleted_by", typeof(string));
    
            var created_dateParameter = created_date.HasValue ?
                new ObjectParameter("created_date", created_date) :
                new ObjectParameter("created_date", typeof(System.DateTime));
    
            var modified_dateParameter = modified_date.HasValue ?
                new ObjectParameter("modified_date", modified_date) :
                new ObjectParameter("modified_date", typeof(System.DateTime));
    
            var deleted_dateParameter = deleted_date.HasValue ?
                new ObjectParameter("deleted_date", deleted_date) :
                new ObjectParameter("deleted_date", typeof(System.DateTime));
    
            var full_nameParameter = full_name != null ?
                new ObjectParameter("full_name", full_name) :
                new ObjectParameter("full_name", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var citizenshipParameter = citizenship.HasValue ?
                new ObjectParameter("citizenship", citizenship) :
                new ObjectParameter("citizenship", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Updateapp_cus_main", idParameter, cus_type_codeParameter, bran_codeParameter, rel_off_codeParameter, titleParameter, firstnameParameter, lastnameParameter, middlenameParameter, dobParameter, age_cat_type_codeParameter, genderParameter, occupation_codeParameter, cus_codeParameter, img_urlParameter, sign_img_urlParameter, marital_statusParameter, child_numParameter, home_type_codeParameter, cus_sinceParameter, cus_other_codeParameter, kin_details_codeParameter, contact_codeParameter, cus_doc_codeParameter, credit_limitParameter, created_byParameter, modified_byParameter, deleted_byParameter, created_dateParameter, modified_dateParameter, deleted_dateParameter, full_nameParameter, statusParameter, citizenshipParameter);
        }
    
        public virtual int app_sp_Updateapp_cus_other_info(Nullable<int> id, string cus_other_code, string verification_id, string ssn, string tax_number, string security_group, string tin_number)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var cus_other_codeParameter = cus_other_code != null ?
                new ObjectParameter("cus_other_code", cus_other_code) :
                new ObjectParameter("cus_other_code", typeof(string));
    
            var verification_idParameter = verification_id != null ?
                new ObjectParameter("verification_id", verification_id) :
                new ObjectParameter("verification_id", typeof(string));
    
            var ssnParameter = ssn != null ?
                new ObjectParameter("ssn", ssn) :
                new ObjectParameter("ssn", typeof(string));
    
            var tax_numberParameter = tax_number != null ?
                new ObjectParameter("tax_number", tax_number) :
                new ObjectParameter("tax_number", typeof(string));
    
            var security_groupParameter = security_group != null ?
                new ObjectParameter("security_group", security_group) :
                new ObjectParameter("security_group", typeof(string));
    
            var tin_numberParameter = tin_number != null ?
                new ObjectParameter("tin_number", tin_number) :
                new ObjectParameter("tin_number", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Updateapp_cus_other_info", idParameter, cus_other_codeParameter, verification_idParameter, ssnParameter, tax_numberParameter, security_groupParameter, tin_numberParameter);
        }
    
        public virtual int app_sp_Updateapp_cus_type(Nullable<int> id, string cus_type_code, string type_name, string status)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var cus_type_codeParameter = cus_type_code != null ?
                new ObjectParameter("cus_type_code", cus_type_code) :
                new ObjectParameter("cus_type_code", typeof(string));
    
            var type_nameParameter = type_name != null ?
                new ObjectParameter("type_name", type_name) :
                new ObjectParameter("type_name", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Updateapp_cus_type", idParameter, cus_type_codeParameter, type_nameParameter, statusParameter);
        }
    
        public virtual int app_sp_Updateapp_doc_type(Nullable<int> id, Nullable<int> doc_type_code, string name, string type)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var doc_type_codeParameter = doc_type_code.HasValue ?
                new ObjectParameter("doc_type_code", doc_type_code) :
                new ObjectParameter("doc_type_code", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Updateapp_doc_type", idParameter, doc_type_codeParameter, nameParameter, typeParameter);
        }
    
        public virtual int app_sp_Updateapp_gender(Nullable<int> id, string gender_code, string sex)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var gender_codeParameter = gender_code != null ?
                new ObjectParameter("gender_code", gender_code) :
                new ObjectParameter("gender_code", typeof(string));
    
            var sexParameter = sex != null ?
                new ObjectParameter("sex", sex) :
                new ObjectParameter("sex", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Updateapp_gender", idParameter, gender_codeParameter, sexParameter);
        }
    
        public virtual int app_sp_Updateapp_home_type(Nullable<int> id, string home_code, string type_name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var home_codeParameter = home_code != null ?
                new ObjectParameter("home_code", home_code) :
                new ObjectParameter("home_code", typeof(string));
    
            var type_nameParameter = type_name != null ?
                new ObjectParameter("type_name", type_name) :
                new ObjectParameter("type_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Updateapp_home_type", idParameter, home_codeParameter, type_nameParameter);
        }
    
        public virtual int app_sp_Updateapp_kin_detail(Nullable<int> id, Nullable<int> kin_type_code, string kin_details_code, string full_name, string firstname, string lastname, string middle, string relationship, string tele_num_rel, string email, string address1, string address2, string zip, string city, string state)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var kin_type_codeParameter = kin_type_code.HasValue ?
                new ObjectParameter("kin_type_code", kin_type_code) :
                new ObjectParameter("kin_type_code", typeof(int));
    
            var kin_details_codeParameter = kin_details_code != null ?
                new ObjectParameter("kin_details_code", kin_details_code) :
                new ObjectParameter("kin_details_code", typeof(string));
    
            var full_nameParameter = full_name != null ?
                new ObjectParameter("full_name", full_name) :
                new ObjectParameter("full_name", typeof(string));
    
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var middleParameter = middle != null ?
                new ObjectParameter("middle", middle) :
                new ObjectParameter("middle", typeof(string));
    
            var relationshipParameter = relationship != null ?
                new ObjectParameter("relationship", relationship) :
                new ObjectParameter("relationship", typeof(string));
    
            var tele_num_relParameter = tele_num_rel != null ?
                new ObjectParameter("tele_num_rel", tele_num_rel) :
                new ObjectParameter("tele_num_rel", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var address1Parameter = address1 != null ?
                new ObjectParameter("address1", address1) :
                new ObjectParameter("address1", typeof(string));
    
            var address2Parameter = address2 != null ?
                new ObjectParameter("address2", address2) :
                new ObjectParameter("address2", typeof(string));
    
            var zipParameter = zip != null ?
                new ObjectParameter("zip", zip) :
                new ObjectParameter("zip", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Updateapp_kin_detail", idParameter, kin_type_codeParameter, kin_details_codeParameter, full_nameParameter, firstnameParameter, lastnameParameter, middleParameter, relationshipParameter, tele_num_relParameter, emailParameter, address1Parameter, address2Parameter, zipParameter, cityParameter, stateParameter);
        }
    
        public virtual int app_sp_Updateapp_kin_type(Nullable<int> id, Nullable<int> kin_type_code, string kin_type_name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var kin_type_codeParameter = kin_type_code.HasValue ?
                new ObjectParameter("kin_type_code", kin_type_code) :
                new ObjectParameter("kin_type_code", typeof(int));
    
            var kin_type_nameParameter = kin_type_name != null ?
                new ObjectParameter("kin_type_name", kin_type_name) :
                new ObjectParameter("kin_type_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Updateapp_kin_type", idParameter, kin_type_codeParameter, kin_type_nameParameter);
        }
    
        public virtual int app_sp_Updateapp_occupation(Nullable<int> id, string occ_code, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var occ_codeParameter = occ_code != null ?
                new ObjectParameter("occ_code", occ_code) :
                new ObjectParameter("occ_code", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Updateapp_occupation", idParameter, occ_codeParameter, nameParameter);
        }
    
        public virtual int app_sp_Updateapp_rel_office(Nullable<int> id, string rel_code, string full_name, string firstname, string lastname, string middlename, string status, string bran_code)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var rel_codeParameter = rel_code != null ?
                new ObjectParameter("rel_code", rel_code) :
                new ObjectParameter("rel_code", typeof(string));
    
            var full_nameParameter = full_name != null ?
                new ObjectParameter("full_name", full_name) :
                new ObjectParameter("full_name", typeof(string));
    
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var middlenameParameter = middlename != null ?
                new ObjectParameter("middlename", middlename) :
                new ObjectParameter("middlename", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var bran_codeParameter = bran_code != null ?
                new ObjectParameter("bran_code", bran_code) :
                new ObjectParameter("bran_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("app_sp_Updateapp_rel_office", idParameter, rel_codeParameter, full_nameParameter, firstnameParameter, lastnameParameter, middlenameParameter, statusParameter, bran_codeParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
